"""Gold-standard retrieval pair tests — REQ-010.

Parameterised over 12 pre-computed query/expected-file pairs stored in
tests/fixtures/sense_test.db (generated by tests/generate_fixtures.py).

Each test case:
  1. Loads a pre-computed query embedding from the query_fixtures table.
  2. Ranks all corpus chunks by raw cosine similarity.
  3. Asserts the expected file appears in the top-3 results.

No OpenAI API calls are made — the fixture DB is a committed artefact.

Coverage (12 pairs):
  Source types : code (2), documentation (6), project_claude (2), trace (2)
  Projects     : project-a (3), project-b (3), project-c (4), root (2)
  Cross-project: Q8, Q9, Q11 — top-3 results span 2+ projects

Design note: raw cosine similarity is used (not the decayed score from
search_chunks) because gold-standard tests verify embedding quality.
Temporal decay is time-dependent and is tested separately in test_decay.py.
"""

import json
import sqlite3
from pathlib import Path

import numpy as np
import pytest

from sense_mcp.server import cosine_similarity

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

FIXTURES_DIR = Path(__file__).parent / "fixtures"
FIXTURE_DB_PATH = FIXTURES_DIR / "sense_test.db"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _rel_path(abs_path: str) -> str:
    """Return the path segment after 'corpus/' from an absolute stored path."""
    parts = Path(abs_path).parts
    try:
        i = parts.index("corpus")
        return str(Path(*parts[i + 1:]))
    except ValueError:
        return abs_path


def _rank_by_similarity(query_emb: np.ndarray) -> list[dict]:
    """Rank all corpus chunks by raw cosine similarity against query_emb.

    Opens the pre-built fixture DB directly — no server state required.
    Returns list of dicts sorted descending by similarity.
    """
    conn = sqlite3.connect(str(FIXTURE_DB_PATH))
    rows = conn.execute(
        "SELECT file_path, project, source_type, embedding FROM chunks"
    ).fetchall()
    conn.close()

    results = []
    for fp, proj, stype, emb_blob in rows:
        chunk_emb = np.frombuffer(emb_blob, dtype=np.float32)
        sim = cosine_similarity(query_emb, chunk_emb)
        results.append({
            "similarity": sim,
            "rel_path": _rel_path(fp),
            "project": proj,
            "source_type": stype,
        })
    results.sort(key=lambda x: x["similarity"], reverse=True)
    return results


# ---------------------------------------------------------------------------
# Load all query fixtures at module level
# (collection time — no pytest fixtures needed, no API calls)
# ---------------------------------------------------------------------------

def _load_query_fixtures() -> list[dict]:
    """Return all gold-standard query fixtures from the pre-built fixture DB."""
    conn = sqlite3.connect(str(FIXTURE_DB_PATH))
    rows = conn.execute(
        "SELECT id, query_text, embedding, expected_files, "
        "expected_source_type, rationale "
        "FROM query_fixtures ORDER BY id"
    ).fetchall()
    conn.close()

    fixtures = []
    for qid, query_text, emb_blob, exp_files_json, exp_source_type, rationale in rows:
        fixtures.append({
            "id": qid,
            "query_text": query_text,
            "embedding": np.frombuffer(emb_blob, dtype=np.float32),
            "expected_files": json.loads(exp_files_json),
            "expected_source_type": exp_source_type,
            "rationale": rationale,
        })
    return fixtures


def _fixture_id(f: dict) -> str:
    short = f["query_text"][:40].replace(" ", "_").replace("/", "-")
    return f"q{f['id']}_{short}"


_QUERY_FIXTURES = _load_query_fixtures()


# ---------------------------------------------------------------------------
# Gold-standard retrieval: expected file in top-3 by cosine similarity
#
# Pairs and their rationale:
#   Q1  documentation  project-a   entrainment in distributed systems → overview.md
#   Q2  code           project-a   Python API for rhythm sync → server.py
#   Q3  trace          project-b   MBA 915 teaching observations → both TRACE files
#   Q4  documentation  project-c   cooperative ownership → README.md
#   Q5  project_claude project-a   project identity / research focus → CLAUDE.md
#   Q6  documentation  project-b   relational conditions for learning → findings.md
#   Q7  code           project-c   cooperative analysis tools → analysis.py
#   Q8  documentation  root        ecosystem overview → root-file.md  [cross-project]
#   Q9  trace          root        Jan-2025 session trace → TRACE_2025-01-01  [cross-project]
#   Q10 documentation  project-c   solidarity economics → README.md
#   Q11 project_claude root        root CLAUDE.md config → CLAUDE.md  [cross-project]
#   Q12 documentation  project-c   Ostrom commons governance → README.md
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "fixture",
    _QUERY_FIXTURES,
    ids=[_fixture_id(f) for f in _QUERY_FIXTURES],
)
class TestGoldStandardRetrieval:
    """Pre-computed query embeddings return expected files in top-3 by similarity.

    Covers REQ-010: each gold-standard (query, expected_file) pair must
    produce a top-3 hit using the fixture corpus embeddings.
    """

    def test_expected_file_in_top3_by_similarity(self, fixture):
        """Expected file must appear in the top-3 most similar chunks.

        At least one file from the expected_files list must rank in the
        top-3 by raw cosine similarity. Multiple expected_files are used
        for Q3 where either trace document satisfies the assertion.
        """
        results = _rank_by_similarity(fixture["embedding"])
        top3_paths = [r["rel_path"] for r in results[:3]]

        matched = any(expected in top3_paths for expected in fixture["expected_files"])
        assert matched, (
            f"\nQuery       : {fixture['query_text']!r}"
            f"\nExpected    : {fixture['expected_files']}"
            f"\nGot top-3   : {top3_paths}"
            f"\nSimilarities: {[round(r['similarity'], 4) for r in results[:3]]}"
            f"\nRationale   : {fixture['rationale']}"
        )

    def test_expected_source_type_present_in_top3(self, fixture):
        """Top-3 results include at least one chunk of the expected source type.

        Confirms the embedding aligns the query with the correct content kind,
        not just a specific file.
        """
        results = _rank_by_similarity(fixture["embedding"])
        top3_types = [r["source_type"] for r in results[:3]]

        assert fixture["expected_source_type"] in top3_types, (
            f"\nQuery              : {fixture['query_text']!r}"
            f"\nExpected type      : {fixture['expected_source_type']!r}"
            f"\nGot top-3 types    : {top3_types}"
            f"\nGot top-3 paths    : {[r['rel_path'] for r in results[:3]]}"
        )


# ---------------------------------------------------------------------------
# Cross-project retrieval: top-3 results span multiple projects
#
# Q8: "Overview of ecosystem connecting multiple research projects"
#     → root-file.md + project-c chunks: projects root + project-c
# Q9: "Session trace from January 2025 fixture"
#     → TRACE_2025-01-01 (root) + project-b trace: projects root + project-b
# Q11: "Root CLAUDE.md project configuration and instructions"
#     → CLAUDE.md (root) + project-a CLAUDE.md: projects root + project-a
# ---------------------------------------------------------------------------

_CROSS_PROJECT_IDS = {8, 9, 11}
_CROSS_PROJECT_FIXTURES = [f for f in _QUERY_FIXTURES if f["id"] in _CROSS_PROJECT_IDS]


@pytest.mark.parametrize(
    "fixture",
    _CROSS_PROJECT_FIXTURES,
    ids=[_fixture_id(f) for f in _CROSS_PROJECT_FIXTURES],
)
class TestCrossProjectRetrieval:
    """Broad queries return top-3 results spanning at least two projects.

    These three queries are ecosystem-scoped — they are not anchored to a
    single project. Verifying that the top-3 results span multiple projects
    confirms that the flat search (no project filter) surfaces content across
    project boundaries when semantically appropriate.

    Covers the 2+ cross-project retrieval requirement of REQ-010.
    """

    def test_top3_spans_multiple_projects(self, fixture):
        """Top-3 results must cover at least 2 distinct projects."""
        results = _rank_by_similarity(fixture["embedding"])
        top3_projects = {r["project"] for r in results[:3]}

        assert len(top3_projects) >= 2, (
            f"\nQuery           : {fixture['query_text']!r}"
            f"\nExpected        : top-3 from 2+ projects"
            f"\nGot projects    : {sorted(top3_projects)}"
            f"\nGot top-3 paths : {[r['rel_path'] for r in results[:3]]}"
        )
